name: Mirror Repo Without Submodules

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4.2.0
      with:
        submodules: true

    - name: Convert submodules to regular directories
      run: |
        git config --global user.email "robot@localz.fr"
        git config --global user.name "Localz's Bot"
        git submodule deinit -f --all
        rm -rf .git/modules/*
        for module in $(git config --file .gitmodules --name-only --get-regexp path | sed 's/submodule\.//g' | sed 's/\.path//g'); do
          git rm --cached $(git config --file .gitmodules --get submodule.$module.path)
        done
        git add .

    - name: Commit converted submodules
      run: |
        git commit -m "Convert submodules to regular directories"

    - name: Mirror repo
      run: |
        git remote add mirror git@github.com:Sinan-Karakaya/test_push_target.git
        git push --mirror mirror
