name: Mirror Repo Without Submodules

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4.2.0
      with:
        submodules: true

    - name: Convert submodules to regular directories
      run: |
        git submodule deinit -f --all
        rm -rf .git/modules/*
        git rm --cached $(git submodule--helper list | awk '{ print $2 }')
        git add .

    - name: Commit converted submodules
      run: |
        git commit -m "Convert submodules to regular directories"

    - name: Mirror repo
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:Sinan-Karakaya/test_push_target.git
        ssh_private_key:
          ${{ secrets.SSH_PRIVATE_KEY }}
