name: Mirroring

on:
    push:
        branches:
            - main

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Sinan-Karakaya/eip-orga-mirror@0a13fa4b4c84be527ca8b7a8d060d488cc2f79d5
        with:
          target_repo_url:
            git@github.com:Sinan-Karakaya/test_push_target.git
          target_subdirectory:
            backend
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
