name: Mirroring

on:
    push:
        branches:
            - main

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Sinan-Karakaya/eip-orga-mirror@c49e3d8953d5703decfee92e71afd7efc1a3cc98
        with:
          target_repo_url:
            git@github.com:Sinan-Karakaya/test_push_target.git
          target_subdirectory:
            backend
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
