name: Mirroring

on:
    push:
        branches:
            - main

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Sinan-Karakaya/eip-orga-mirror@19ff62a90bd45ebb12d69567566fb171adfc2c4d
        with:
          target_repo_url:
            git@github.com:Sinan-Karakaya/test_push_target
          target_subdirectory:
            backend
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
