name: Mirror Repo Without Submodules

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: [self-hosted, linux, localz]

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4.2.0
      with:
        submodules: true

    - name: Convert submodules to regular directories
      run: |
        # Loop through each submodule and make it a normal directory
        git submodule deinit -f --all       # Deinitialize all submodules
        rm -rf .git/modules/*               # Remove submodule references from the Git configuration
        git rm --cached $(git submodule--helper list | awk '{ print $2 }')  # Remove cached submodule paths from git
        git add .                           # Add files from the submodules into the main repo

    - name: Commit converted submodules
      run: |
        git commit -m "Convert submodules to regular directories"

    - name: Mirror repo
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          git@github.com:Sinan-Karakaya/test_push_target.git
        ssh_private_key:
          ${{ secrets.SSH_PRIVATE_KEY }}
