name: Mirroring

on:
    push:
        branches:
            - main

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: Sinan-Karakaya/eip-orga-mirror@a4a4f7c36291b71fde96727ab0d4be6763ba00c3
        with:
          target_repo_url:
            git@github.com:Sinan-Karakaya/test_push_target
          target_subdirectory:
            backend
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
